# Generated by Django 4.0.4 on 2022-05-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworksnzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
